import { NextResponse } from 'next/server';
import { db, castVote } from '@/lib/db';

export const runtime = 'nodejs';

/**
 * Like, dislike, or take it back. The voter id is generated by the browser and
 * is only as trustworthy as that: it prevents a double click from counting
 * twice, not a determined person from voting a hundred times. Real one-person
 * one-vote needs accounts, which this preview does not have.
 */
export async function POST(req: Request) {
  const b = (await req.json().catch(() => ({}))) as Record<string, unknown>;
  const gameId = String(b.gameId ?? '');
  const voter = String(b.voter ?? '');
  const value = Number(b.value);

  if (!db.prepare('SELECT 1 FROM games WHERE id = ?').get(gameId)) {
    return NextResponse.json({ error: 'Unknown game' }, { status: 404 });
  }
  if (!/^[a-f0-9-]{16,64}$/i.test(voter)) {
    return NextResponse.json({ error: 'Malformed voter id' }, { status: 400 });
  }
  if (value !== -1 && value !== 0 && value !== 1) {
    return NextResponse.json({ error: 'A vote is -1, 0 or 1' }, { status: 400 });
  }
  return NextResponse.json(castVote(gameId, voter, value as -1 | 0 | 1));
}
